# Generated by Django 4.1.5 on 2023-01-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classModel',
            fields=[
                ('class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('class_level', models.CharField(default='None', max_length=10)),
                ('section', models.CharField(default='None', max_length=10)),
                ('capacity', models.IntegerField()),
                ('num_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='McqModel',
            fields=[
                ('question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='None', max_length=500)),
                ('option_a', models.CharField(default='None', max_length=100)),
                ('option_b', models.CharField(default='None', max_length=100)),
                ('option_c', models.CharField(default='None', max_length=100)),
                ('option_d', models.CharField(default='None', max_length=100)),
                ('correct_option', models.CharField(default='None', max_length=100)),
                ('weight', models.IntegerField(default=1)),
                ('unit_number', models.IntegerField(default=-1)),
                ('topic', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=50)),
                ('student_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('attendance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.studentmodel')),
                ('student_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
            ],
        ),
    ]
