# Generated by Django 4.1.5 on 2023-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='None', max_length=50)),
                ('password', models.CharField(default='None', max_length=50)),
                ('name', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
