# Generated by Django 4.1.5 on 2023-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqmodel',
            name='correct_option',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcqmodel',
            name='option_a',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcqmodel',
            name='option_b',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcqmodel',
            name='option_c',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcqmodel',
            name='option_d',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcqmodel',
            name='question',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
