# Generated by Django 4.1.5 on 2023-01-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0002_alter_mcqmodel_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqmodel',
            name='topic',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mcqmodel',
            name='unit_number',
            field=models.IntegerField(default=-1),
        ),
    ]
