# Generated by Django 4.1.5 on 2023-03-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0002_teachermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_class',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='teacher_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.teachermodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('marks_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('evaluationType', models.CharField(max_length=20)),
                ('totalMarks', models.IntegerField()),
                ('obtainedMarks', models.IntegerField()),
                ('class_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
                ('student_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('enrollment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('class_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
                ('student_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.studentmodel')),
            ],
        ),
    ]
