# Generated by Django 4.1.5 on 2023-04-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0003_remove_studentmodel_student_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('attendance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(default='P', max_length=1)),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.teachermodel')),
                ('teacher_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
            ],
        ),
    ]
