# Generated by Django 4.1.5 on 2023-04-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0004_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
