# Generated by Django 4.1.5 on 2023-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0005_alter_teachermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('roomNumber', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('Class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.teachermodel')),
            ],
        ),
    ]
