# Generated by Django 4.1.5 on 2023-04-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0006_teacherschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherschedule',
            name='date',
        ),
    ]
