# Generated by Django 4.1.5 on 2023-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0007_remove_teacherschedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='time',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='durationMinutes',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
