# Generated by Django 4.1.5 on 2023-04-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0008_rename_time_teacherschedule_starttime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('announcement_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
