# Generated by Django 4.1.5 on 2023-04-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0010_teacherannouncement_class_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAnnouncement',
        ),
    ]
