# Generated by Django 4.1.5 on 2023-04-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0012_teacherannouncement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAnnouncement',
        ),
    ]
