# Generated by Django 4.1.5 on 2023-04-12 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0013_delete_teacherannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('announcement_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('class_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.classmodel')),
            ],
        ),
    ]
