# Generated by Django 4.1.5 on 2023-04-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0014_teacherannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherannouncement',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliLearnBackendAPI.teachermodel'),
        ),
    ]
