# Generated by Django 4.1.5 on 2023-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliLearnBackendAPI', '0017_uploadedbook_classname_uploadedbook_txt_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqmodel',
            old_name='unit_number',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='mcqmodel',
            name='bookName',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mcqmodel',
            name='className',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
